server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 35b66638bb7e28cb87d0567a6d94dbfbda4dd6f74b17ac51993e5f6f00b8f3d1
    url: jdbc:postgresql://ec2-52-5-247-46.compute-1.amazonaws.com:5432/d1rdorotgvncq8
    username: wklsgcuxdgnnvp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

